name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        
      - name: Build
        run: npm run build
        
      - name: Deploy to gh-pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Remove existing gh-pages branch
          git push origin --delete gh-pages || true
          
          # Create new gh-pages branch
          git checkout --orphan gh-pages
          
          # Remove everything
          git rm -rf .
          
          # Copy only dist contents
          cp -r dist/* .
          
          # Add all files
          git add .
          
          # Commit
          git commit -m "Deploy to GitHub Pages"
          
          # Push
          git push origin gh-pages
          
          # Go back to main
          git checkout main